title: IU Alumni
email: d.kolokolov@innopolis.university
description: >- # this means to ignore newlines until "baseurl:"
  The IU Alumni project is designed to help university students keep track of events, 
  register for elective courses, manage attendance, 
  and request passes for various university-related purposes.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://dimoninbirsk.github.io/IU-Alumni-Static-Site-Generated-Documentation" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  dimoninbirsk

# Build settings
theme: minima
plugins:
  - jekyll-feed